In [ ]:
import json

In [ ]:
file_name=r"Books_small_10000.json"
with open (file_name) as f:
    for line in f:
        print(line)  
        break

{"reviewerID": "A1F2H80A1ZNN1N", "asin": "B00GDM3NQC", "reviewerName": "Connie Correll", "helpful": [0, 0], "reviewText": "I bought both boxed sets, books 1-5.  Really a great series!  Start book 1 three weeks ago and just finished book 5.  Sloane Monroe is a great character and being able to follow her through both private life and her PI life gets a reader very involved!  Although clues may be right in front of the reader, there are twists and turns that keep one guessing until the last page!  These are books you won't be disappointed with.", "overall": 5.0, "summary": "Can't stop reading!", "unixReviewTime": 1390435200, "reviewTime": "01 23, 2014"}



In [206]:
import random

class Sentiment:
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    POSITIVE = "POSITIVE"

class Review:
    def __init__(self, text, score):
        self.text = text
        self.score = score
        self.sentiment = self.get_sentiment()
        
    def get_sentiment(self):
        if self.score <= 2:
            #return 'NEGATIVE'
            return Sentiment.NEGATIVE 
        elif self.score == 3:
            #return 'NEUTRAL'
            return Sentiment.NEUTRAL
        else: #Score of 4 or 5
            #return"POSITIVE"
            return Sentiment.POSITIVE
        
class ReviewContainer:
    def __init__(self, reviews):
        self.reviews = reviews
        
    def get_text(self):
        return [x.text for x in self.reviews]
    
    def get_sentiment(self):
        return [x.sentiment for x in self.reviews]
        
    def evenly_distribute(self):
        negative = list(filter(lambda x: x.sentiment == Sentiment.NEGATIVE, self.reviews))
        positive = list(filter(lambda x: x.sentiment == Sentiment.POSITIVE, self.reviews))
        positive_shrunk = positive[:len(negative)]
        self.reviews = negative + positive_shrunk
        random.shuffle(self.reviews)

In [207]:
reviews = []
with open(file_name) as f:
    for line in f:
        review = json.loads(line)
        reviews.append(Review(review['reviewText'],review['overall']))
len(reviews)

10000

In [208]:
print("Text:",reviews[1].text)
print("Score:",reviews[1].score)
print("Sentiment:",reviews[1].sentiment)

Text: I enjoyed this short book. But it was way way to short ....I can see how easily it would have been to add several chapters.
Score: 3.0
Sentiment: NEUTRAL


In [209]:
from sklearn.model_selection import train_test_split

In [ ]:
training_set, test_set = train_test_split(reviews, test_size=0.33,random_state=40)

train_container = ReviewContainer(training_set)

test_container = ReviewContainer(test_set)

In [ ]:
train_container.evenly_distribute()
train_x = train_container.get_text()
train_y = train_container.get_sentiment()

test_container.evenly_distribute()
test_x = test_container.get_text()
test_y = test_container.get_sentiment()

print(train_y.count(Sentiment.POSITIVE))
print(train_y.count(Sentiment.NEGATIVE))

423
423


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer = TfidfVectorizer() 

# vectorizer.fit(x)
# train_x_vectors = vectorizer.transform(x)
train_x_vectors = vectorizer.fit_transform(train_x) 
test_x_vectors = vectorizer.transform(test_x)

In [258]:
from sklearn import svm
svm_model = svm.SVC(kernel='linear')
svm_model.fit(train_x_vectors, train_y)

SVC(kernel='linear')

In [ ]:
print(test_x[1])
print('Predicted sentiment:',svm_model.predict(test_x_vectors[1]))

This is an engaging, interesting, thoughtful book by a former atheist who gradually, kicking and screaming, converts to Catholicism.  A well-told conversion story with depth and humor.
Predicted sentiment: ['POSITIVE']


In [284]:
from sklearn.tree import DecisionTreeClassifier
Dec_model = DecisionTreeClassifier()
Dec_model.fit(train_x_vectors,train_y)

DecisionTreeClassifier()

In [285]:
Dec_model.predict(test_x_vectors[1])

array(['POSITIVE'], dtype='<U8')

In [286]:
from sklearn.naive_bayes import GaussianNB

NB_model = GaussianNB()
NB_model.fit(train_x_vectors.toarray(),train_y) #"toarray" converts a sparse matrix to a dense numpy array

GaussianNB()

In [287]:
NB_model.predict(test_x_vectors[1].toarray())

array(['POSITIVE'], dtype='<U8')

In [288]:
from sklearn.linear_model import LogisticRegression

LR_model = LogisticRegression()
LR_model.fit(train_x_vectors,train_y)

LogisticRegression()

In [289]:
LR_model.predict(test_x_vectors[1])

array(['POSITIVE'], dtype='<U8')

In [290]:
print("SVM Classifier Accuracy:",svm_model.score(test_x_vectors,test_y)) 
print("Decision Tree Classifier Accuracy:",Dec_model.score(test_x_vectors,test_y))
print("Naive Bayes Classifier Accuracy:",NB_model.score(test_x_vectors.toarray(),test_y))
print("Logistic Regression Classifier Accuracy:",LR_model.score(test_x_vectors.toarray(),test_y))

SVM Classifier Accuracy: 0.8552036199095022
Decision Tree Classifier Accuracy: 0.6764705882352942
Naive Bayes Classifier Accuracy: 0.6176470588235294
Logistic Regression Classifier Accuracy: 0.8506787330316742


In [291]:
from sklearn.metrics import f1_score

# f1_score(test_y, svm_model.predict(test_x_vectors), average= None, 
#          labels=[Sentiment.POSITIVE, Sentiment.NEUTRAL, Sentiment.NEGATIVE])
#SVM 
f1_score(test_y, svm_model.predict(test_x_vectors), average= None, 
         labels=[Sentiment.POSITIVE, Sentiment.NEGATIVE])

array([0.85253456, 0.85777778])

In [ ]:
f1_score(test_y, Dec_model.predict(test_x_vectors), average= None, 
         labels=[Sentiment.POSITIVE, Sentiment.NEGATIVE])

array([0.66510539, 0.68708972])

In [ ]:
f1_score(test_y, NB_model.predict(test_x_vectors.toarray()), average= None, 
         labels=[Sentiment.POSITIVE, Sentiment.NEUTRAL, Sentiment.NEGATIVE])

C:\Users\yesmi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))


array([0.60788863, 0.        , 0.62693157])

In [294]:
#Logistic Regression
f1_score(test_y, LR_model.predict(test_x_vectors), average= None, 
         labels=[Sentiment.POSITIVE, Sentiment.NEGATIVE])

array([0.84862385, 0.85267857])

In [295]:
test = ["very good. excellent book","terrible book, do not recommend", "wouldn't recommend it to my worst enenmies"]

vect_test = vectorizer.transform(test)

NB_model.predict(vect_test.toarray())

array(['NEGATIVE', 'NEGATIVE', 'NEGATIVE'], dtype='<U8')

In [296]:
from sklearn.model_selection import GridSearchCV

parameters = {'kernel': ('linear', 'rbf'), 'C': (1,4,8,16,32)}

svc = svm.SVC()
clf = GridSearchCV(svc, parameters, cv=5)

clf.fit(train_x_vectors, train_y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': (1, 4, 8, 16, 32), 'kernel': ('linear', 'rbf')})

In [297]:
clf.score(test_x_vectors, test_y)

0.8484162895927602

In [ ]:
import pickle

with open (r'Models\SVM_sentiment_classifier.pkl'
          ,'wb') as f:

    pickle.dump(clf, f)

In [ ]:
with open (r'Models\SVM_sentiment_classifier.pkl', 'rb') as f:
    loaded_clf = pickle.load(f)

In [302]:
test_x[0]

"Constance Cherry's book is a wealth of information.  What a fresh way to look at worship planning!  I highly recommend to worship planners and worshipers alike!"

In [301]:
loaded_clf.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')